### PR TITLE
[plugin-mailq] mailq/postfix: Fix mail queue count regexp capture when it's `1`

### LINKED ISSUE #1185: [plugin-mailq/postfix] bug: Mail queue count `1` reflected as `0` instead
## Background

When used with Postfix, the `mackerel-plugin-mail` does not correctly reflect the mail queue count value when it is `1`; the value reflected by the plugin is `0`. This is happening because of the following faulty regex expression (at line `31`) used to match the output of the `postqueue -p` command:

https://github.com/mackerelio/mackerel-agent-plugins/blob/92751c4cb3925b828d66a0937cb3b3f93a3c38ea/mackerel-plugin-mailq/lib/main.go#L27-L32

When the mail queue contains only one item, the word `Requests` is singularized as `Request`. 

### Examples
Here's an example output of the `postqueue -p` command when there's only one item:
```
$ postqueue -p
----Queue ID----- --Size-- ---Arrival Time---- --Sender/Recipient------
4Vgbvc4GLXz40kq      11613 Fri May 17 06:02:04 test@example.com
(Host or domain name not found. Name service error for name=localdomain.local type=MX: Host not found, try again)
                                               local@localdomain.local

-- 11 Kbytes in 1 Request.

$ mackerel-plugin-mailq -M postfix
mailq.count     0       1715930097
```

Here's an example output of the `postqueue -p` command when there is more than one item:
```
$ postqueue -p
----Queue ID----- --Size-- ---Arrival Time---- --Sender/Recipient------
4Vgbw31rzhz40tJ      11798 Fri May 17 06:02:27 test@example.com
(Host or domain name not found. Name service error for name=localdomain.local type=MX: Host not found, try again)
                                               local@localdomain.local

4Vgbvc4FYCz40nD      11605 Fri May 17 06:02:04 test@example.com
(Host or domain name not found. Name service error for name=localdomain.local type=MX: Host not found, try again)
                                               local@localdomain.local

-- 22 Kbytes in 2 Requests.

$ mackerel-plugin-mailq -M postfix
mailq.count     2       1715930362
```

## Proposal

This can be easily fixed by updating the faulty regex expression to also match the word `Request` when there's only one item in the mail queue. I'll have a PR for this later.

### PR DESCRIPTION
**Pull request by yongjiajun**
Fixes #1185 

This PR fixes the mail queue count regexp capture for Postfix when there's only 1 item in the mail queue.

**Note/Update**: The tests in the package modified are passing as I've tested them locally.

### CODE REVIEW

File: mackerel-plugin-mailq/lib/fixtures/postqueue [hunk 1]
```diff
@@ -5,6 +5,12 @@
 [[ $1 != -p ]] && exit 1
 
 TEST_MAILQ_COUNT=${TEST_MAILQ_COUNT:-0}
+POSTQUEUE_REQUEST_LABEL="Request"
```
Comment (lufia) [inline mackerel-plugin-mailq/lib/fixtures/postqueue:8]: typo?
```suggestion
POSTQUEUE_REQUEST_LABEL="Requests"
```

File: mackerel-plugin-mailq/lib/main_test.go [hunk 2]
```diff
@@ -267,15 +287,21 @@ func TestFetchMetricsPostfix(t *testing.T) {
...
-	{
-		os.Setenv("TEST_MAILQ_COUNT", "42")
+	for _, tc := range []struct {
+		mailqCount int
+	}{
+		{mailqCount: 42},
+		{mailqCount: 0},
+		{mailqCount: 1}, // #1185
+	} {
+		os.Setenv("TEST_MAILQ_COUNT", strconv.Itoa(tc.mailqCount))
```
Comment (lufia) [inline mackerel-plugin-mailq/lib/main_test.go:297]: [note] In general, Go 1.17 or higher, it would be better to use *testing.T.Setenv*.

But to keep consistency this use *os.Setenv* here intentionally because all test cases other than that still use *os.Getenv.*

**Review by lufia — COMMENTED** [review]
@yongjiajun Thank you, I think almost ok but please kindly confirm my suggestion

File: mackerel-plugin-mailq/lib/fixtures/postqueue (hunk 1 above)
Comment (yongjiajun) [reply mackerel-plugin-mailq/lib/fixtures/postqueue]: Thank you for catching that!

**Review by lufia — APPROVED** [review]
We will release in a few days.

**Comment by yongjiajun** [comment]
@lufia Thank you!
